const schoolExcuses = [
  "I didn’t skip school, I was just at school for so long it felt like a second home.",
  "I didn’t skip school, I was just stuck in class until time forgot about me.",
  "I didn’t skip school, I was just in the building so long the teachers thought I worked there.",
  "I didn’t skip school, I was just trapped in a never‑ending lesson loop.",
  "I didn’t skip school, I was just waiting for the final bell that never came.",
  "I didn’t skip school, I was just attending bonus school hours nobody told me about.",
  "I didn’t skip school, I was just walking the halls until the halls got tired of me.",
  "I didn’t skip school, I was just stuck in a class that refused to end.",
  "I didn’t skip school, I was just doing extended learning against my will.",
  "I didn’t skip school, I was just waiting for a teacher who said ‘one more minute’ 47 times.",
  "I didn’t skip school, I was just in a meeting with the clock because it wasn’t moving.",
  "I didn’t skip school, I was just completing overtime education hours.",
  "I didn’t skip school, I was just stuck in the cafeteria time‑warp zone.",
  "I didn’t skip school, I was just waiting for dismissal like it was a rare event.",
  "I didn’t skip school, I was just in a class that turned into a trilogy.",
  "I didn’t skip school, I was just doing extra school because the day wouldn’t end.",
  "I didn’t skip school, I was just trapped in a lesson that had DLC content.",
  "I didn’t skip school, I was just stuck in a hallway side quest.",
  "I didn’t skip school, I was just waiting for the teacher to stop talking since yesterday.",
  "I didn’t skip school, I was just in a class that accidentally became a sleepover.",
  "I didn’t skip school, I was just attending the extended edition of school.",
  "I didn’t skip school, I was just stuck in a lesson that refused to end credits.",
  "I didn’t skip school, I was just waiting for the bell that went on vacation.",
  "I didn’t skip school, I was just in a classroom that forgot what time was.",
  "I didn’t skip school, I was just doing the deluxe version of school hours.",
  "I didn’t skip school, I was just stuck in a teacher monologue that lasted centuries.",
  "I didn’t skip school, I was just attending the after‑after‑after school program.",
  "I didn’t skip school, I was just waiting for dismissal like it was a rare boss drop.",
  "I didn’t skip school, I was just trapped in a classroom that refused to release me.",
  "I didn’t skip school, I was just experiencing the infinite school glitch.",
  "I didn’t skip school, I was just stuck in a class that refused to release me into the wild.",
  "I didn’t skip school, I was just waiting for the bell that forgot its job.",
  "I didn’t skip school, I was just trapped in a lesson that turned into a whole season finale.",
  "I didn’t skip school, I was just in a classroom that accidentally became a time loop.",
  "I didn’t skip school, I was just attending school overtime like a dedicated employee.",
  "I didn’t skip school, I was just stuck in a hallway that had no exit cutscene.",
  "I didn’t skip school, I was just waiting for the teacher to stop talking since last week.",
  "I didn’t skip school, I was just in a class that kept adding bonus rounds.",
  "I didn’t skip school, I was just doing extended learning because the day wouldn’t end.",
  "I didn’t skip school, I was just attending the ultra‑deluxe edition of school hours.",
  "I didn’t skip school, I was just stuck in a lesson that had a surprise sequel.",
  "I didn’t skip school, I was just waiting for dismissal like it was a rare achievement unlock.",
  "I didn’t skip school, I was just trapped in a classroom that forgot how clocks work.",
  "I didn’t skip school, I was just doing the extended cut of education.",
  "I didn’t skip school, I was just stuck in a teacher monologue that lasted multiple eras.",
  "I didn’t skip school, I was just attending the after‑school program’s after‑school program.",
  "I didn’t skip school, I was just waiting for the bell that went missing in action.",
  "I didn’t skip school, I was just in a classroom that accidentally became a survival challenge.",
  "I didn’t skip school, I was just stuck in a lesson that refused to roll credits.",
  "I didn’t skip school, I was just experiencing the legendary long‑day school event."
];